### PR TITLE
Updated composer.json to use later version of guzzle.

### PR DESCRIPTION
**Pull request by alpha1125**

### CODE REVIEW

**Comment by jakubjo** [comment]
Looking through [closed PR history](https://github.com/mailchimp/mailchimp-marketing-php/pulls?q=is%3Apr+is%3Aclosed) MailChimp apparently does not want us to use their library.

**Comment by angelsk** [comment]
Looking at the history - they've said to open PR's on this repo: https://github.com/mailchimp/mailchimp-client-lib-codegen - because this library repo is automatically generated and will be overwritten each time.

**Comment by angelsk** [comment]
@alpha1125 Looks like you need to submit your change for this file: https://github.com/mailchimp/mailchimp-client-lib-codegen/blob/master/swagger-config/marketing/php/templates/composer.mustache

**Comment by alpha1125** [comment]
Thanks. looks like someone already put a PR in for this change. https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/72

**Pull request closed without merging**
