### PR TITLE
Allow the usage of the guzzle 7

### PR DESCRIPTION
**Pull request by WardVH**
Hi,

Please allow the usage of the latest version of Guzzle (https://github.com/guzzle/guzzle/releases/tag/7.0.0)

Kind regards,
Ward

### CODE REVIEW

**Comment by netom** [comment]
Yes, this would be nice.

**Comment by lordkerwin** [comment]
any news of this working with Guzzle 7.X??

**Comment by WardVH** [comment]
@lordkerwin We have been using Guzzle 7.X for well over a few months now with this package in production and haven't encountered any issues so far.

**Comment by mc-hannah-morrison** [comment]
Thanks for your feedback! We updated the SDK to use guzzle 7

**Pull request closed without merging**
